### ISSUE TITLE
Add DFR3Viewer support for multi-hazard fragilities

### ISSUE THREAD

**Issue by navarroc** [IN-CORE/incore-ui#119]
Once the service adds support for multi-hazard fragilities (e.g. Earthquake + Tsunami), the DFR3 viewer will need to support this as well so they can be filtered .

**Comment by longshuicy** [comment]
We need to add menu item for the dropdown

And check if the filter works on the endpoint. 

Example:
https://incore.ncsa.illinois.edu/dfr3/api/fragilities?limit=50&skip=0&hazard=earthquake+tsunami
