### ISSUE TITLE
Add a clickable link to the dataType field in the Data Viewer table.

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-ui#121]
We want to add a hyperlink to the semantic service dataset type in the metadata of the data that we show on the DataViewer component.

Effect:
- A pop-up window or a new tab to show the HTML view of the dataset type definition.

<img width="2543" alt="Screenshot 2023-06-26 at 10 47 18 AM" src="https://github.com/IN-CORE/incore-ui/assets/32737711/38541314-3efe-4186-9b33-2bdb56f0d66f">

**Comment by Vismayak** [comment]
I have only changed one file and though it was a simple change, I reformatted the file and moved the complex logic to another function in the same file
