### ISSUE TITLE
Create a SemanticsViewer component

### ISSUE THREAD

**Issue by Rashmil-1999** [IN-CORE/incore-ui#122]
Create a new Viewer component called semanticViewer/typeViewer to the dropdown on the web-tools in the navbar.

Should contain:
- Search bar
- Place to view all the types listed
- A detailed view space for the type when clicked on
- A download button to download the .json file to their device.

Would look similar to this component.

<img width="2543" alt="Screenshot 2023-06-26 at 10 47 18 AM" src="https://github.com/IN-CORE/incore-ui/assets/32737711/9f03abd7-43f3-44bd-b9ff-f3dcaedbf9df">

**Comment by Vismayak** [comment]
<img width="990" alt="image" src="https://github.com/IN-CORE/incore-ui/assets/16596733/12ff34bf-d860-4847-b0c8-df957e88c0a5">
<img width="991" alt="image" src="https://github.com/IN-CORE/incore-ui/assets/16596733/e9d441e5-8829-4df2-bbdc-2d4fed92d16d">
