### ISSUE TITLE
Make github action to make the correct docker container tag

### ISSUE THREAD

**Issue by ywkim312** [IN-CORE/incore-ui#155]
The final release docker container tag contains the word 'v' in its tag name and this should be removed.

**Comment by Rashmil-1999** [comment]
@ywkim312 Has this got something to do with how I created the tag?

**Comment by ywkim312** [comment]
> @ywkim312 Has this got something to do with how I created the tag?

no it is about github action when it generates docker images tag with v as the first character. You're release tag is find. It should start using the word 'v' but docker container image, we decided not to use 'v'

**Comment by ywkim312** [comment]
The yaml file for github action looks correct. When it gets merged to main, it creates the correct versioned docker container. However, the release also creates the container that starts with "v" since the tag is will be "v***". Closing the issue
