### ISSUE TITLE
Remodel INCORE home page

### ISSUE THREAD

**Issue by Vismayak** [IN-CORE/incore-ui#170]
Change the home page to look similar to 
https://www.astropy.org/

**Comment by navarroc** [comment]
Can you add a label indicating how much effort you think this is?

**Comment by Vismayak** [comment]
Discussion 1 Changes:
[ ] Create collapsible div for all versions with url to new release 
[ ] Expand the text - Run your scientific analyses that model the impact of natural hazards on a community and the resilience of those communities.

**Comment by Vismayak** [comment]
- [ ] Add link for current version
- [ ] Bug of pushing logo when collapsible is opened
