### ISSUE TITLE
tracking frontend usage by each viewer

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-ui#37]
data viewer usage
dfr3 viewer usage
hazard viewer usage

Right now we only have the information that user is using the frontend but there is no way to differentiate which viewer they are on. Nor can we differentiate from the service point of view that is "frontend" or "pyincore" or "POSTman" is calling certain service endpoint.

Need to think of ways to do that

@robkooper 
- Facebook hacky way??
- Google metrics
- additional parameter in the endpoint to differentiate the source?

**Comment by robkooper** [comment]
Couple of options here:
1. we add a tracking piece of code that is called when we select an option from the menu. This will allow us to track when somebody selects documenttion, lab or any of the viewers.
2. add a small image to the webpage (with a ?time=${date now}) to make sure it is not cached
3. add a marker to the call to the /api/data etc so we know the call is from the dataviewer.
